use tauri_plugin_sql::{Migration, MigrationKind};

/// The database lives in the OS app-data directory, not next to the binary,
/// so it survives app updates and is covered by Time Machine.
const DB_URL: &str = "sqlite:kotoba.db";

/// Migrations are generated by drizzle-kit and embedded verbatim.
/// Never hand-edit SQL here — regenerate with `bun run db:generate`.
fn migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "init",
            sql: include_str!("../../drizzle/0000_init.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "lesson_blocks",
            sql: include_str!("../../drizzle/0001_lesson_blocks.sql"),
            kind: MigrationKind::Up,
        },
    ]
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations(DB_URL, migrations())
                .build(),
        )
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
