use tauri_plugin_sql::{Migration, MigrationKind};

/// The database lives in the OS app-data directory, not next to the binary,
/// so it survives app updates and is covered by Time Machine.
const DB_URL: &str = "sqlite:kotoba.db";

/// Migrations are generated by drizzle-kit and embedded verbatim.
/// Never hand-edit SQL here — regenerate with `bun run db:generate`.
fn migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "init",
            sql: include_str!("../../drizzle/0000_init.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "lesson_blocks",
            sql: include_str!("../../drizzle/0001_lesson_blocks.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "card_authoring_key",
            sql: include_str!("../../drizzle/0002_card_authoring_key.sql"),
            kind: MigrationKind::Up,
        },
    ]
}

/// Copies the bundled, pre-seeded course into place on first launch.
///
/// Without this a downloaded build opens to an empty Learn screen, because the
/// course is authored by a script that lives in the repo. The bundled copy is
/// already migrated, so the SQL plugin's migration pass sees version 3 applied
/// and no-ops.
///
/// Only ever runs when no database exists. An existing file means the learner
/// has progress, and overwriting that would be unforgivable.
fn install_bundled_course(app: &tauri::App) -> Result<(), Box<dyn std::error::Error>> {
    use tauri::Manager;

    let dir = app.path().app_data_dir()?;
    std::fs::create_dir_all(&dir)?;
    let target = dir.join("kotoba.db");

    if target.exists() {
        return Ok(());
    }

    match app.path().resolve("resources/course.db", tauri::path::BaseDirectory::Resource) {
        Ok(seed) if seed.exists() => {
            std::fs::copy(&seed, &target)?;
            log::info!("installed bundled course at {}", target.display());
        }
        _ => log::info!("no bundled course found; starting with an empty database"),
    }
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations(DB_URL, migrations())
                .build(),
        )
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            // Must happen before the frontend calls Database.load().
            if let Err(e) = install_bundled_course(app) {
                log::error!("could not install bundled course: {e}");
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
