/**
 * Component names and meanings.
 *
 * KRADFILE decomposes kanji into parts but gives no names — this table
 * supplies them, and it is the hand-authored half of the kanji track.
 * Names are written for this course; they are not Heisig's keywords or
 * WaniKani's radical names, both of which are copyrighted.
 *
 * KRADFILE uses stand-in characters for radicals that have no convenient
 * codepoint of their own — 汁 for 氵, 艾 for 艹, 込 for 辶, 扎 for 扌 and so
 * on. `DISPLAY` maps those back to the shape you actually see in a kanji,
 * because being taught that 海 contains "汁" would be actively confusing.
 */

/** kradfile stand-in → the form that actually appears in a character. */
export const DISPLAY: Record<string, string> = {
  汁: '氵', 艾: '艹', 込: '辶', 扎: '扌', 忙: '忄', 犯: '犭', 礼: '礻',
  初: '衤', 阡: '阝', 邦: '阝', 疔: '疒', 杰: '灬', 刈: '刂', 買: '罒',
  个: '𠆢', 乞: '𠂉', 并: '丷', 尚: '⺌', 化: '化', 竹: '竹',
}

export const display = (c: string) => DISPLAY[c] ?? c

type Comp = [name: string, note?: string]

/**
 * 253 components, which is every part KRADFILE uses.
 * Order here is irrelevant; lookup is by character.
 */
export const COMPONENTS: Record<string, Comp> = {
  /* --- strokes and frames --- */
  '一': ['one', 'a single horizontal stroke'],
  '｜': ['stick', 'a single vertical stroke'],
  'ノ': ['slash', 'a stroke falling to the left'],
  '丶': ['drop', 'a single dot'],
  '亅': ['hook', 'a vertical stroke with a hook'],
  '乙': ['second', 'a bent stroke; also "the second one"'],
  '二': ['two'],
  '亠': ['lid', 'a dot on a horizontal line, sitting on top'],
  '冂': ['open box', 'open at the bottom'],
  '囗': ['enclosure', 'a closed box around something'],
  '凵': ['container', 'open at the top'],
  '匚': ['box on its side', 'open to the right'],
  '冖': ['cover', 'a flat crown'],
  '宀': ['roof', 'a house roof with a chimney'],
  '广': ['lean-to', 'a roof with one wall'],
  '厂': ['cliff', 'an overhang'],
  '尸': ['flag', 'also a bent body or corpse'],
  '廴': ['stretch', 'a long stride'],
  '辶': ['road', 'movement, going'],
  '込': ['road', 'movement, going'],
  '冫': ['ice', 'two frozen drops'],
  '氵': ['water', 'three drops'],
  '汁': ['water', 'three drops at the left'],
  '灬': ['fire below', 'four dots of flame'],
  '杰': ['fire below', 'four dots of flame'],
  '艹': ['grass', 'plants on top'],
  '艾': ['grass', 'plants on top'],
  '扌': ['hand', 'the hand radical on the left'],
  '扎': ['hand', 'the hand radical on the left'],
  '忄': ['heart', 'the heart radical on the left'],
  '忙': ['heart', 'the heart radical on the left'],
  '犭': ['beast', 'an animal on the left'],
  '犯': ['beast', 'an animal on the left'],
  '礻': ['altar', 'the spirit or ritual radical'],
  '礼': ['altar', 'the spirit or ritual radical'],
  '衤': ['clothing', 'the garment radical'],
  '初': ['clothing', 'the garment radical'],
  '阝': ['mound or village', 'left = hill, right = village'],
  '阡': ['hill', 'the left-hand mound'],
  '邦': ['village', 'the right-hand settlement'],
  '疒': ['sickness', 'a person on a bed'],
  '疔': ['sickness', 'a person on a bed'],
  '刂': ['blade', 'a knife on the right'],
  '刈': ['blade', 'a knife on the right'],
  '罒': ['net', 'an eye lying on its side'],
  '買': ['net', 'an eye lying on its side'],
  '𠆢': ['roof of people', 'the person radical as a lid'],
  '个': ['roof of people', 'the person radical as a lid'],
  '𠂉': ['top hat', 'a small angled cap'],
  '乞': ['top hat', 'a small angled cap'],
  '丷': ['horns', 'two small strokes above'],
  '并': ['horns', 'two small strokes above'],
  '⺌': ['small crown', 'three strokes on top'],
  '尚': ['small crown', 'three strokes on top'],
  '彳': ['step', 'the left half of a crossroads — walking'],
  '爿': ['split wood', 'the left half of a tree'],
  '几': ['table'],
  '勹': ['wrap', 'arms enclosing something'],
  '匕': ['spoon', 'also a seated person'],
  '厶': ['private', 'a small curl'],
  '卩': ['seal', 'a kneeling figure'],
  '巛': ['river', 'flowing water'],
  '彡': ['hair', 'three sweeping strokes'],
  '爻': ['crossing lines'],
  '丆': ['stroke', 'a small angled mark'],

  /* --- people and body --- */
  '人': ['person'],
  '化': ['change', 'a person and a spoon — transformation'],
  '儿': ['legs', 'a person seen from behind'],
  '女': ['woman'],
  '子': ['child'],
  '大': ['big', 'a person with arms spread'],
  '小': ['small'],
  '士': ['scholar', 'also a warrior'],
  '老': ['old', 'an aged person'],
  '父': ['father'],
  '母': ['mother'],
  '毋': ['do not', 'the mother shape crossed out'],
  '氏': ['clan', 'a family name'],
  '臣': ['retainer', 'a servant of the court'],
  '身': ['body'],
  '自': ['self', 'a nose — Japanese speakers point at their nose for "me"'],
  '目': ['eye'],
  '耳': ['ear'],
  '口': ['mouth', 'also an opening or a box'],
  '舌': ['tongue'],
  '歯': ['tooth'],
  '牙': ['fang'],
  '首': ['neck', 'also a head'],
  '頁': ['page', 'originally a head'],
  '面': ['face', 'also a surface'],
  '心': ['heart', 'the mind and emotions'],
  '手': ['hand'],
  '足': ['foot', 'also "enough"'],
  '止': ['stop', 'a footprint'],
  '疋': ['leg'],
  '又': ['again', 'originally a right hand'],
  '寸': ['inch', 'a hand with a measuring mark'],
  '肉': ['meat', 'flesh'],
  '月': ['moon', 'in compounds often means flesh or a body part'],
  '骨': ['bone'],
  '血': ['blood'],
  '毛': ['fur', 'hair'],
  '髟': ['long hair'],
  '皮': ['skin', 'hide'],
  '欠': ['lack', 'a person with an open mouth — yawning'],
  '夂': ['walk slowly', 'a trailing foot'],
  '舛': ['opposing feet'],
  '尢': ['lame', 'a bent leg'],
  '匕': ['spoon', 'also a seated person'],
  '亡': ['perish', 'death, absence'],
  '歹': ['bare bones', 'death'],
  '鬼': ['ghost', 'a demon'],

  /* --- nature --- */
  '日': ['sun', 'also a day'],
  '曰': ['say', 'a mouth with a line — speaking'],
  '月': ['moon'],
  '木': ['tree', 'wood'],
  '本': ['origin', 'a tree with a mark at its root'],
  '禾': ['grain', 'a bending rice plant'],
  '米': ['rice'],
  '麦': ['wheat'],
  '黍': ['millet'],
  '竹': ['bamboo'],
  '草': ['grass'],
  '花': ['flower'],
  '瓜': ['melon'],
  '豆': ['bean'],
  '韭': ['leek'],
  '土': ['earth', 'soil, ground'],
  '山': ['mountain'],
  '川': ['river'],
  '水': ['water'],
  '雨': ['rain'],
  '气': ['vapour', 'steam'],
  '火': ['fire'],
  '石': ['stone'],
  '玉': ['jewel'],
  '王': ['king', 'as a component usually means jewel'],
  '金': ['metal', 'also gold and money'],
  '田': ['rice field'],
  '里': ['village', 'a field over earth'],
  '谷': ['valley'],
  '穴': ['hole', 'a cave'],
  '生': ['life', 'birth, growing'],
  '青': ['blue', 'also green and freshness'],
  '白': ['white'],
  '赤': ['red'],
  '黄': ['yellow'],
  '黒': ['black'],
  '色': ['colour'],
  '风': ['wind'],
  '風': ['wind'],
  '雲': ['cloud'],
  '虫': ['insect', 'also small creatures'],
  '魚': ['fish'],
  '鳥': ['bird'],
  '隹': ['small bird', 'a short-tailed bird'],
  '羽': ['feathers', 'wings'],
  '犬': ['dog'],
  '牛': ['cow'],
  '羊': ['sheep'],
  '馬': ['horse'],
  '豕': ['pig'],
  '豸': ['badger', 'a clawed animal'],
  '鹿': ['deer'],
  '亀': ['turtle'],
  '黽': ['frog'],
  '鼠': ['rat'],
  '竜': ['dragon'],
  '飛': ['fly'],
  '角': ['horn', 'also a corner'],
  '爪': ['claw', 'a hand reaching down'],
  '巴': ['comma shape', 'a swirl'],
  '屮': ['sprout'],
  '禹': ['creeping thing'],
  '隶': ['capture', 'a hand catching a tail'],
  '辰': ['dragon of the zodiac', 'also a time sign'],
  '艮': ['stopping', 'a stubborn shape'],

  /* --- objects and tools --- */
  '刀': ['sword', 'a blade'],
  '斤': ['axe'],
  '戈': ['halberd', 'a long-handled weapon'],
  '弓': ['bow', 'archery'],
  '矢': ['arrow'],
  '矛': ['spear'],
  '殳': ['weapon', 'a hand holding a club'],
  '車': ['vehicle', 'a cart seen from above'],
  '舟': ['boat'],
  '衣': ['clothing'],
  '巾': ['cloth', 'a hanging towel'],
  '糸': ['thread', 'silk'],
  '幺': ['tiny thread', 'a small coil'],
  '皿': ['dish', 'a plate'],
  '缶': ['can', 'a jar'],
  '酉': ['sake jar', 'alcohol, fermentation'],
  '鬯': ['sacrificial wine'],
  '鬲': ['cauldron'],
  '鼎': ['ritual tripod'],
  '食': ['eat', 'food'],
  '飠': ['food', 'the eating radical'],
  '斗': ['ladle', 'a measure'],
  '匚': ['box on its side'],
  '冊': ['book', 'bound bamboo strips'],
  '聿': ['brush', 'a hand holding a writing brush'],
  '文': ['writing', 'a pattern or text'],
  '言': ['words', 'speech'],
  '音': ['sound'],
  '龠': ['flute'],
  '鼓': ['drum'],
  '示': ['altar', 'ritual, the divine'],
  '門': ['gate'],
  '戸': ['door', 'a single-leaf door'],
  '瓦': ['roof tile'],
  '井': ['well'],
  '工': ['work', 'a craftsman\'s tool'],
  '力': ['power', 'strength'],
  '耒': ['plough'],
  '網': ['net'],
  '革': ['leather', 'treated hide'],
  '韋': ['tanned leather'],
  '黹': ['embroidery'],
  '鬥': ['fighting', 'two figures grappling'],
  '卜': ['divination', 'a crack in a bone'],
  '爿': ['bed on its side'],
  '片': ['slice', 'one half'],
  '用': ['use'],
  '玄': ['mysterious', 'dark'],
  '幸': ['fortune'],
  '辛': ['bitter', 'spicy, harsh'],
  '甘': ['sweet'],
  '香': ['fragrance'],
  '鹵': ['salt'],
  '走': ['run'],
  '行': ['go', 'also a line or a row'],
  '至': ['arrive'],
  '高': ['tall'],
  '長': ['long', 'also a leader'],
  '広': ['wide'],
  '方': ['direction', 'also a method'],
  '比': ['compare', 'two people side by side'],
  '非': ['not', 'wings turned away from each other'],
  '无': ['nothing'],
  '無': ['nothing', 'absence'],
  '品': ['goods', 'three mouths — items'],
  '員': ['member'],
  '貝': ['shell', 'money, value'],
  '見': ['see', 'an eye on legs'],
  '釆': ['distinguish'],
  '里': ['village'],
  '麻': ['hemp'],
  '齊': ['align', 'orderly'],
  '斉': ['align', 'orderly'],
  '鼻': ['nose'],
  '奄': ['cover', 'suddenly'],
  '岡': ['ridge', 'a hill'],
  '滴': ['drop of liquid'],

  /* --- numbers, counters, abstract --- */
  '十': ['ten', 'a cross'],
  '五': ['five'],
  '九': ['nine'],
  '元': ['origin', 'the beginning'],
  '世': ['generation', 'the world'],
  '及': ['reach', 'extend to'],
  '久': ['long time'],
  '乃': ['thereupon', 'an old connective'],
  '也': ['also', 'an old copula'],
  '勿': ['must not'],
  '弋': ['stake', 'a marker post'],
  '干': ['dry', 'also to interfere'],
  '巨': ['huge'],
  '屯': ['barracks', 'gathered'],
  '尤': ['especially'],
  '已': ['already'],
  '廾': ['two hands', 'lifting together'],
  '癶': ['footsteps departing'],
  '彑': ['snout'],
  '夕': ['evening', 'a half moon'],
  '夂': ['trailing foot'],
  '亠': ['lid'],
  '八': ['eight', 'also splitting apart'],
  'ハ': ['eight', 'two strokes spreading apart'],
  'ヨ': ['hand', 'a hand shape like the katakana'],
  'マ': ['ma shape', 'a small hook like the katakana'],
  'ユ': ['yu shape', 'a small box like the katakana'],
  '立': ['stand'],
  '入': ['enter'],
  '止': ['stop'],
  '西': ['west'],
  '虍': ['tiger'],
  '而': ['and yet', 'a beard'],
  '攵': ['strike', 'a hand with a stick — action, causing'],
  '支': ['branch', 'support'],
  '免': ['exempt', 'avoid'],
  '臼': ['mortar', 'a grinding bowl'],
  '舛': ['contrary'],
}

/** Human-readable name, falling back to the character itself. */
export function componentName(c: string): string {
  const key = DISPLAY[c] ?? c
  return COMPONENTS[key]?.[0] ?? COMPONENTS[c]?.[0] ?? key
}

export function componentNote(c: string): string | undefined {
  const key = DISPLAY[c] ?? c
  return COMPONENTS[key]?.[1] ?? COMPONENTS[c]?.[1]
}

export const knownComponent = (c: string) => {
  const key = DISPLAY[c] ?? c
  return !!(COMPONENTS[key] ?? COMPONENTS[c])
}
